#!/bin/bash

SELFPWD="$(realpath "$(dirname "$0")")"

find "$SELFPWD/src" -name '*.rs'|xargs xtr -d lw_tray -o lw_tray.pot

for po in locale/*/LC_MESSAGES
    do
        msgmerge "$po/lw_tray.po" lw_tray.pot -o "$po/lw_tray.po"
        msgfmt "$po/lw_tray.po" -o "$po/lw_tray.mo"
done
