[build]
target = "x86_64-unknown-linux-gnu"
rustflags = ["-C", "strip=symbols", "-Z", "remap-cwd-prefix="]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]